# Generated by Django 5.1.3 on 2024-11-26 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('main_photo', models.ImageField(blank=True, null=True, upload_to='providers/')),
                ('description', models.TextField()),
            ],
        ),
    ]
